### ISSUE TITLE
Upgrade to Terraform v0.12

### ISSUE THREAD

**Issue by joakimhellum** [moofish32/terraform-provider-cidr#9]
Hi,

Thanks for this provider since it fit's our use case very well. We've been testing it for a while and intend  to use it widely in our organization. Do you have any plans to upgrade this provider to support Terraform v0.12? 

I think (roughly) the necessary steps would be:

1. Upgrade to Go 1.11
  1.1. Update versions in `.travis.yml` and `README.md`

2. Switch to Go Modules
  2.1. Run `go mod init`
  2.2. Delete `Gopkg.*` and `vendor/`
  2.3. Run `go mod tidy`
  2.4. Run `go mod vendor`
  2.5. Remove `govendor` from GNUMakefile
  2.6. Set environment variables for Go Modules in `.travis.yml`

3. Upgrade to Terraform v0.12
  3.1. Run `go get github.com/hashicorp/terraform@pluginsdk-v0.12-early9`

Noticed there might be plans to finally adopt this provider and make it "official", in which case I guess this issue can be closed since it means the provider will also be supported by HashiCorp and eventually upgraded to v0.12

Note: I already tested this provder with Terraform v0.12 quite a bit. Would be happy to make a PR for this.

Thanks!

**Comment by moofish32** [comment]
I welcome the PR and the updates if you are willing to do the work. If not I am planning to make one more push in 0.12 assuming Hashicorp might finally allow the plugin as official.

**Comment by joakimhellum** [comment]
Did most of the work in this [forked repo](https://github.com/innovationnorway/terraform-provider-cidr/tree/v0.12-upgrade), but didn't finish testing yet. Will try to finish testing the provider and TravisCI in the next few days, then create the PR. If you're already planning to do this, then please don't feel like you need to wait for my PR, because it might be slow.
Thanks again for making this provider, it is very much needed :smile:
